/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DCliente;
import Negocio.NCliente;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuCliente extends javax.swing.JFrame {
        int ID;
	int CI;
        String Nombre;
	String Sexo;
    NCliente cliente;
    
    public CuCliente() throws ClassNotFoundException {
        initComponents();
         this.setLocationRelativeTo(this);
         cliente=new NCliente();
        TableColumnModel columnModel = TCLIENTES.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(1).setPreferredWidth(90);
         columnModel.getColumn(2).setPreferredWidth(60);
           columnModel.getColumn(3).setPreferredWidth(20);
       TXTID.setText(cliente.ObetenerCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TXTNOMBBRE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTCI = new javax.swing.JTextField();
        CBSEXO = new javax.swing.JComboBox();
        TXTID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TCLIENTES = new javax.swing.JTable();
        BTNEDITAR = new javax.swing.JButton();
        BTNREGISTRAR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        BTNNUEVO = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        BTNMOSTRAR1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clientes.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 172, 158));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "REGISTRO DE CLIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(TXTNOMBBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 300, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NOMBRE COMPLETO");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CARNET IDENTIDAD");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));
        jPanel1.add(TXTCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 300, -1));

        CBSEXO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELEGIR SEXO", "M", "F" }));
        jPanel1.add(CBSEXO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, -1));
        jPanel1.add(TXTID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 300, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ID");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 460, 158));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TCLIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Sexo", "Carnet"
            }
        ));
        jScrollPane1.setViewportView(TCLIENTES);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 218, 640, 250));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        jPanel3.add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 110, 40));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        jPanel3.add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 150, 40));

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        jPanel3.add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, 40));

        BTNNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNNUEVO.setText("NUEVO");
        BTNNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNUEVOActionPerformed(evt);
            }
        });
        jPanel3.add(BTNNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, 40));

        BTNSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR.setText("SALLIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        jPanel3.add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 470, 110, 40));

        BTNMOSTRAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        BTNMOSTRAR1.setText("MOSTRAR");
        BTNMOSTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMOSTRAR1ActionPerformed(evt);
            }
        });
        jPanel3.add(BTNMOSTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 650, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here:
        try {
            ID=Integer.valueOf(TXTID.getText());
            Nombre=TXTNOMBBRE.getText();
            Sexo=CBSEXO.getSelectedItem().toString();
            CI=Integer.valueOf(TXTCI.getText());
            String resultado=cliente.actualizar(ID, CI, Nombre, Sexo);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"DATOS INVALIDOS "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        String resutado="";
        try {
             ID=Integer.valueOf(TXTID.getText());
             if (TXTNOMBBRE.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "INTRODUZCA NOMBRE COMPLETO");
                return;
             }
             Nombre=TXTNOMBBRE.getText();
             if (CBSEXO.getSelectedIndex()==0) {
                JOptionPane.showMessageDialog(null, "SELECCIONE UN TIPO DE SEXO");
                return;
            }
             Sexo=CBSEXO.getSelectedItem().toString().substring(0, 1);
             if (TXTCI.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "INTRODUZCA CARNET DE IDENTIDAD");
                return;
             }
             CI=Integer.valueOf(TXTCI.getText());
             resutado=cliente.insertar(ID, CI, Nombre, Sexo);
             JOptionPane.showMessageDialog(null, resutado);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,resutado+" "+ e.getMessage());
        }

    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            //        String cod=JOptionPane.showInputDialog(null,"INTRODUZCA CODIGO");
            String[] table=cliente.Consultabuscar(TXTCI.getText());
            TXTID.setText(table[0]);
            TXTCI.setText(table[1]);
            TXTNOMBBRE.setText(table[2]);
            CBSEXO.setSelectedItem(table[3]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "CLIENTE NO ENCONTRADO ");
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNUEVOActionPerformed
        // TODO add your handling code here:
        
        TXTCI.setText("");
        TXTNOMBBRE.setText("");
        CBSEXO.setSelectedIndex(0);
        TXTID.setText(cliente.ObetenerCodigo());
    }//GEN-LAST:event_BTNNUEVOActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNMOSTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMOSTRAR1ActionPerformed
        // TODO add your handling code here:
        try {
            String[][] tabla=cliente.ListaDeClientes();
            DefaultTableModel modelo= (DefaultTableModel) TCLIENTES.getModel();
            int filas=modelo.getRowCount();
            if (filas>0) {
                for (int i = 0; i < filas; i++) {
                    modelo.removeRow(0);
                }
            }
            for (int i = 0; i <tabla.length ; i++) {
                modelo.addRow(new Object[]{tabla[i][0],tabla[i][1],tabla[i][2],tabla[i][3]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DE SISTEMA "+e.getMessage());
        }
        
    }//GEN-LAST:event_BTNMOSTRAR1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuCliente().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CuCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNMOSTRAR1;
    private javax.swing.JButton BTNNUEVO;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JComboBox CBSEXO;
    private javax.swing.JTable TCLIENTES;
    public javax.swing.JTextField TXTCI;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTNOMBBRE;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
