/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.NEncomienda;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuEncomienda extends javax.swing.JFrame {
    int cod;
    String descripcion;
    float precio;
    int cantidad;
    static int idGuia;
    NEncomienda encommienda;
    /**
     * Creates new form CuEncomienda
     */
    public CuEncomienda() throws ClassNotFoundException {
        initComponents();
        this.setLocationRelativeTo(this);
        encommienda=new NEncomienda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNSALIR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        BTNEDITAR = new javax.swing.JButton();
        TXTPRECIO = new javax.swing.JTextField();
        TXTCANTIDAD = new javax.swing.JTextField();
        LBLPRECIO = new javax.swing.JLabel();
        LBLCANTIDAD = new javax.swing.JLabel();
        TXTCODENCOMIENDA = new javax.swing.JTextField();
        LBLDESCRIPCION1 = new javax.swing.JLabel();
        LBLDESCRIPCION = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTDESCRIPCION = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BTNREGISTRAR = new javax.swing.JButton();
        BTNNUEVO = new javax.swing.JButton();
        TXTIDGUIA = new javax.swing.JTextField();
        LBLCANTIDAD1 = new javax.swing.JLabel();
        BTNGUIA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 170, 40));

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 170, -1));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 170, 40));
        getContentPane().add(TXTPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 70, -1));
        getContentPane().add(TXTCANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 70, -1));

        LBLPRECIO.setText("PRECIO");
        getContentPane().add(LBLPRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        LBLCANTIDAD.setText("CANTIDAD");
        getContentPane().add(LBLCANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(TXTCODENCOMIENDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 70, -1));

        LBLDESCRIPCION1.setText("CODIGO");
        getContentPane().add(LBLDESCRIPCION1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        LBLDESCRIPCION.setText("DESCRIPCION");
        getContentPane().add(LBLDESCRIPCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        TXTDESCRIPCION.setColumns(20);
        TXTDESCRIPCION.setRows(5);
        jScrollPane1.setViewportView(TXTDESCRIPCION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 420, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE ENCOMIENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 350, 40));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 170, 40));

        BTNNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNNUEVO.setText("NUEVO");
        BTNNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(BTNNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 170, 40));
        getContentPane().add(TXTIDGUIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 70, -1));

        LBLCANTIDAD1.setText("ID GUIA");
        getContentPane().add(LBLCANTIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        BTNGUIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new.png"))); // NOI18N
        BTNGUIA.setText("REGISTRAR GUIA");
        BTNGUIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGUIAActionPerformed(evt);
            }
        });
        getContentPane().add(BTNGUIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar(){
        TXTCODENCOMIENDA.setText("");
        TXTPRECIO.setText("");
        TXTCANTIDAD.setText("");
        TXTDESCRIPCION.setText("");
    }
    
    private void BTNNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNUEVOActionPerformed
        // TODO add your handling code here:
        limpiar();
        TXTCODENCOMIENDA.setText(encommienda.ObetenerCodigoNuevo());  
        TXTIDGUIA.setText(String.valueOf(idGuia));
    }//GEN-LAST:event_BTNNUEVOActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        String resultado="";
        try {
            cod=Integer.valueOf(TXTCODENCOMIENDA.getText());
            precio=Float.valueOf(TXTPRECIO.getText());
            cantidad=Integer.valueOf(TXTCANTIDAD.getText());
            descripcion=TXTDESCRIPCION.getText();
            idGuia=Integer.valueOf(TXTIDGUIA.getText());
            if (idGuia<=0) {
                JOptionPane.showMessageDialog(null, "ERROR DE ID DE GUIA");
                return;
            }
            resultado=encommienda.insertar(cod, descripcion, precio, cantidad, idGuia);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, resultado+" "+e.getMessage());
        }
        
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here:
        try {
            cod=Integer.valueOf(TXTCODENCOMIENDA.getText());
            precio=Float.valueOf(TXTPRECIO.getText());
            cantidad=Integer.valueOf(TXTCANTIDAD.getText());
            descripcion=TXTDESCRIPCION.getText();
            idGuia=Integer.valueOf(TXTIDGUIA.getText());
            String resultado=encommienda.acutalizar(cod, descripcion, precio, cantidad, idGuia);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR DE DATOS "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            //        String cod=JOptionPane.showInputDialog(null,"INTRODUZCA CODIGO");
            String[] v=encommienda.Consultabuscar(TXTCODENCOMIENDA.getText());
            TXTCODENCOMIENDA.setText(v[0]);
            TXTPRECIO.setText(v[2]);
            TXTCANTIDAD.setText(v[3]);
            TXTDESCRIPCION.setText(v[1]);
            TXTIDGUIA.setText(v[4]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EL CODIGO NO EXISTE "+e.getMessage());
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNGUIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGUIAActionPerformed
        CuGuia guia=new CuGuia();
        guia.setVisible(true);
    }//GEN-LAST:event_BTNGUIAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuEncomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuEncomienda().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CuEncomienda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNGUIA;
    private javax.swing.JButton BTNNUEVO;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JLabel LBLCANTIDAD;
    private javax.swing.JLabel LBLCANTIDAD1;
    private javax.swing.JLabel LBLDESCRIPCION;
    private javax.swing.JLabel LBLDESCRIPCION1;
    private javax.swing.JLabel LBLPRECIO;
    private javax.swing.JTextField TXTCANTIDAD;
    private javax.swing.JTextField TXTCODENCOMIENDA;
    private javax.swing.JTextArea TXTDESCRIPCION;
    private javax.swing.JTextField TXTIDGUIA;
    private javax.swing.JTextField TXTPRECIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
