/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.NCliente;
import Negocio.NGuia;
import static Presentacion.CuEncomienda.idGuia;
import Reportes.Reporte;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_transporte.Controlador;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuGuia extends javax.swing.JFrame {
    int Codigo;
    String Fecha;
    float Costo;
    String EstadoDeCobro;
    int codPlanilla;
    int codEmpleado=1200;
    int ciEnvia;
    int ciRecibe;
    NGuia guia;
    /**
     * Creates new form CuGuia
     */
    public CuGuia() {
        try {
            initComponents();
            guia=new NGuia();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuGuia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTCOD = new javax.swing.JTextField();
        TXTFECHA = new javax.swing.JTextField();
        TXTCOSTO = new javax.swing.JTextField();
        CBESTADO = new javax.swing.JComboBox<String>();
        TXTCODPLANILLA = new javax.swing.JTextField();
        TXTCARNETENVIA = new javax.swing.JTextField();
        TXTCARNETRECIBE = new javax.swing.JTextField();
        BTNNUEVO = new javax.swing.JButton();
        BTNREGISTRAR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        BTNEDITAR = new javax.swing.JButton();
        BTNVERCLIENTE = new javax.swing.JButton();
        BTNVERPLANILLA = new javax.swing.JButton();
        TBNIMPRIMIR = new javax.swing.JButton();
        BTNSALIR = new javax.swing.JButton();
        LBLFECHA = new javax.swing.JLabel();
        LBLCOSTO = new javax.swing.JLabel();
        LBLCODIGO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LBLCOSTO1 = new javax.swing.JLabel();
        LBLCOSTO2 = new javax.swing.JLabel();
        LBLCOSTO3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(TXTCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, -1));
        getContentPane().add(TXTFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 90, -1));

        TXTCOSTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCOSTOActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 90, -1));

        CBESTADO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ESTADO DE COBRO", "CANCELADO", "POR COBRAR" }));
        getContentPane().add(CBESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 137, -1));

        TXTCODPLANILLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCODPLANILLAActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCODPLANILLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 90, -1));

        TXTCARNETENVIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCARNETENVIAActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCARNETENVIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 90, -1));

        TXTCARNETRECIBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCARNETRECIBEActionPerformed(evt);
            }
        });
        getContentPane().add(TXTCARNETRECIBE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 90, -1));

        BTNNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNNUEVO.setText("NUEVO");
        BTNNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(BTNNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 150, 40));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 150, 40));

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 150, -1));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        getContentPane().add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, 40));

        BTNVERCLIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        BTNVERCLIENTE.setText("CLIENTES");
        BTNVERCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVERCLIENTEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNVERCLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 40));

        BTNVERPLANILLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock1.png"))); // NOI18N
        BTNVERPLANILLA.setText("PLANILLA");
        BTNVERPLANILLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVERPLANILLAActionPerformed(evt);
            }
        });
        getContentPane().add(BTNVERPLANILLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 150, 40));

        TBNIMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_imprimir.gif"))); // NOI18N
        TBNIMPRIMIR.setText("Imprimir");
        TBNIMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBNIMPRIMIRActionPerformed(evt);
            }
        });
        getContentPane().add(TBNIMPRIMIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 150, -1));

        BTNSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR.setText("SALLIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 150, 40));

        LBLFECHA.setText("FECHA");
        getContentPane().add(LBLFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        LBLCOSTO.setText("COSTO");
        getContentPane().add(LBLCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        LBLCODIGO.setText("CODIGO");
        getContentPane().add(LBLCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRO DE GUIA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, 40));

        LBLCOSTO1.setText("CODIGO PLANILLA");
        getContentPane().add(LBLCOSTO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        LBLCOSTO2.setText("CI ENVIA");
        getContentPane().add(LBLCOSTO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        LBLCOSTO3.setText("CI RECIBE");
        getContentPane().add(LBLCOSTO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiar(){
        TXTCOD.setText("");
        TXTCOSTO.setText("");
        TXTCARNETENVIA.setText("");
        TXTCARNETRECIBE.setText("");
        TXTCODPLANILLA.setText("");
        TXTFECHA.setText("");
        CBESTADO.setSelectedIndex(0);
    }
    
    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        String resultado="";
        try {
            Codigo=Integer.valueOf(TXTCOD.getText());
            Costo=Float.valueOf(TXTCOSTO.getText());
            Fecha=TXTFECHA.getText();
            ciEnvia=Integer.valueOf(TXTCARNETENVIA.getText());
            ciRecibe=Integer.valueOf(TXTCARNETRECIBE.getText());
            codPlanilla=Integer.valueOf(TXTCODPLANILLA.getText());
            EstadoDeCobro=CBESTADO.getSelectedItem().toString();
            resultado=guia.insertar(Codigo, Fecha, Costo, EstadoDeCobro, codPlanilla, codEmpleado, ciEnvia, ciRecibe);
            CuEncomienda.idGuia=Codigo;
            JOptionPane.showMessageDialog(rootPane, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,resultado+ e.getMessage());
        }

    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            String cod=(TXTCOD.getText());
            String[] v=guia.Consultabuscar(cod);
            TXTCOD.setText(v[0]);
            TXTCOSTO.setText(v[2]);
            TXTCARNETENVIA.setText(v[6]);
            TXTCARNETRECIBE.setText(v[7]);
            TXTCODPLANILLA.setText(v[4]);
            TXTFECHA.setText(v[1]);
            if (v[3].charAt(0)=='C') {
                CBESTADO.setSelectedIndex(1);
            }else{
                CBESTADO.setSelectedIndex(2);
            }
            CuEncomienda.idGuia=Integer.valueOf(TXTCOD.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EL CODIGO NO EXISTE "+e.getMessage());
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here:
        String resultado="";
        try {
            Codigo=Integer.valueOf(TXTCOD.getText());
            Costo=Float.valueOf(TXTCOSTO.getText());
            Fecha=TXTFECHA.getText();
            ciEnvia=Integer.valueOf(TXTCARNETENVIA.getText());
            ciRecibe=Integer.valueOf(TXTCARNETENVIA.getText());
            codPlanilla=Integer.valueOf(TXTCODPLANILLA.getText());
            EstadoDeCobro=CBESTADO.getSelectedItem().toString();
            resultado=guia.acutalizar(Codigo, Fecha, Costo, EstadoDeCobro, codPlanilla, codEmpleado, ciEnvia, ciRecibe);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR DE DATOS "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void BTNVERCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVERCLIENTEActionPerformed
        try {
            // TODO add your handling code here:
            CuCliente cliente=new CuCliente();
            cliente.setVisible(true);
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "ERROR DEL SISTEMA");
        }
    }//GEN-LAST:event_BTNVERCLIENTEActionPerformed

    private void BTNNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNUEVOActionPerformed
        // TODO add your handling code here:
                limpiar();
                TXTCOD.setText(guia.GenerarCodigo());
    }//GEN-LAST:event_BTNNUEVOActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
        CuEncomienda.idGuia=Integer.valueOf(TXTCOD.getText());
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void TXTCOSTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCOSTOActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_TXTCOSTOActionPerformed

    private void TXTCODPLANILLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCODPLANILLAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCODPLANILLAActionPerformed

    private void TXTCARNETENVIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCARNETENVIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCARNETENVIAActionPerformed

    private void TXTCARNETRECIBEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCARNETRECIBEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCARNETRECIBEActionPerformed

    private void BTNVERPLANILLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVERPLANILLAActionPerformed
        // TODO add your handling code here:
        CuPlanilla planilla;
        try {
            planilla = new CuPlanilla();
            planilla.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuGuia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BTNVERPLANILLAActionPerformed

    private void TBNIMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBNIMPRIMIRActionPerformed
    if(Controlador.esNumero(TXTCOD.getText()))  
        Reporte.Guia(Integer.parseInt(TXTCOD.getText()));        // TODO add your handling code here:
        
    }//GEN-LAST:event_TBNIMPRIMIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuGuia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new CuGuia().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNNUEVO;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JButton BTNVERCLIENTE;
    private javax.swing.JButton BTNVERPLANILLA;
    private javax.swing.JComboBox<String> CBESTADO;
    private javax.swing.JLabel LBLCODIGO;
    private javax.swing.JLabel LBLCOSTO;
    private javax.swing.JLabel LBLCOSTO1;
    private javax.swing.JLabel LBLCOSTO2;
    private javax.swing.JLabel LBLCOSTO3;
    private javax.swing.JLabel LBLFECHA;
    private javax.swing.JButton TBNIMPRIMIR;
    private javax.swing.JTextField TXTCARNETENVIA;
    private javax.swing.JTextField TXTCARNETRECIBE;
    private javax.swing.JTextField TXTCOD;
    private javax.swing.JTextField TXTCODPLANILLA;
    private javax.swing.JTextField TXTCOSTO;
    private javax.swing.JTextField TXTFECHA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
