/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Negocio.NHojaDeSalida;
import Reportes.Reporte;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_transporte.Controlador;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuHojaDeSalida extends javax.swing.JFrame {
    int id;
    float costo;
    String hora;
    int codPlanilla;
    NHojaDeSalida hojaDeSalida;
    /**
     * Creates new form CuHojaDeSalida
     */
    public CuHojaDeSalida() throws ClassNotFoundException {
        initComponents();
        hojaDeSalida=new NHojaDeSalida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLCODIG = new javax.swing.JLabel();
        TXTCOD = new javax.swing.JTextField();
        LBLORIGEN = new javax.swing.JLabel();
        TXTPLANILLA = new javax.swing.JTextField();
        LBLMODELO = new javax.swing.JLabel();
        HORA = new javax.swing.JTextField();
        BTNPLANILLA = new javax.swing.JButton();
        BTNMOSTRAR = new javax.swing.JButton();
        BTNEDITAR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        BTNREGISTRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TRUTAS = new javax.swing.JTable();
        BTNSALIR = new javax.swing.JButton();
        LBLCOSTO = new javax.swing.JLabel();
        TXTCOSTO = new javax.swing.JTextField();
        BTNREGISTRAR1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "REGISTRO DE HOJAS DE SALIDAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLCODIG.setText("CODIGO");
        jPanel1.add(LBLCODIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        jPanel1.add(TXTCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, -1));

        LBLORIGEN.setText("CODIGO DE PLANILLA");
        jPanel1.add(LBLORIGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(TXTPLANILLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));

        LBLMODELO.setText("HORA");
        jPanel1.add(LBLMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(HORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));

        BTNPLANILLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        BTNPLANILLA.setText("PLANILLAS");
        BTNPLANILLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPLANILLAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNPLANILLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 150, 40));

        BTNMOSTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock1.png"))); // NOI18N
        BTNMOSTRAR.setText("MOSTRAR");
        BTNMOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMOSTRARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNMOSTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 40));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 150, 40));

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 150, -1));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 150, 40));

        TRUTAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "HORA", "FECHA", "CODIGO PLANILLA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TRUTAS.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(TRUTAS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 470, 160));

        BTNSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR.setText("SALLIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 110, 40));

        LBLCOSTO.setText("COSTO");
        jPanel1.add(LBLCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        TXTCOSTO.setText("4");
        jPanel1.add(TXTCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, -1));

        BTNREGISTRAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNREGISTRAR1.setText("  NUEVO");
        BTNREGISTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRAR1ActionPerformed(evt);
            }
        });
        jPanel1.add(BTNREGISTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_imprimir.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 490, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNPLANILLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPLANILLAActionPerformed
        try {
            // TODO add your handling code here:
            new CuPlanilla().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuLugar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNPLANILLAActionPerformed

    private void BTNMOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMOSTRARActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel modelo= (DefaultTableModel) TRUTAS.getModel();
            String fecha=JOptionPane.showInputDialog(null, "INTRODUZCA FECHA");
            String[][] table=hojaDeSalida.listaDeHojasDeSalidas(fecha);
            int Tfila=modelo.getRowCount();
            if (Tfila>0) {
                for (int i = 0; i <Tfila ; i++) {
                    modelo.removeRow(0);
                }
            }
            for (int i = 0; i <table.length ; i++) {
                modelo.addRow(new Object[]{table[i][0],table[i][1],table[i][2],table[i][3]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO EXISTEN HOJAS DE SALIDAS EN ESA FECHA "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNMOSTRARActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here:
        try {
            id=Integer.valueOf(TXTCOD.getText());
            costo=Float.valueOf(TXTCOSTO.getText());
            hora=HORA.getText();
            codPlanilla=Integer.valueOf(TXTPLANILLA.getText());
            String resultado=hojaDeSalida.acutalizar(id, costo, hora, codPlanilla);
            JOptionPane.showMessageDialog(null,resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR DE DATOS "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            int cod=Integer.valueOf(TXTCOD.getText());
            String[] table=hojaDeSalida.Consultabuscar(TXTCOD.getText());
            TXTCOD.setText(table[0]);
            TXTCOSTO.setText(table[1]);
            HORA.setText(table[2]);
            TXTPLANILLA.setText(table[3]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "EL CODIGO NO EXISTE "+e.getMessage());
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        String resutado="";
        try {
            resutado=hojaDeSalida.insertar(Integer.valueOf(TXTCOD.getText()),Float.valueOf(TXTCOSTO.getText()),
                HORA.getText(),Integer.valueOf(TXTPLANILLA.getText()));
            JOptionPane.showMessageDialog(null, resutado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"DATOS INVALIDOS "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNREGISTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRAR1ActionPerformed
        // TODO add your handling code here:
        TXTCOSTO.setText("");
        TXTPLANILLA.setText("");
        HORA.setText("");
        TXTCOD.setText(String.valueOf(hojaDeSalida.ObetenerCodigoNuevo()));
    }//GEN-LAST:event_BTNREGISTRAR1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              if(Controlador.esNumero(TXTCOD.getText())){    
            Reporte.HojaDeSalida(Integer.parseInt(TXTCOD.getText()));}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuHojaDeSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuHojaDeSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuHojaDeSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuHojaDeSalida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuHojaDeSalida().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CuHojaDeSalida.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNMOSTRAR;
    private javax.swing.JButton BTNPLANILLA;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNREGISTRAR1;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JTextField HORA;
    private javax.swing.JLabel LBLCODIG;
    private javax.swing.JLabel LBLCOSTO;
    private javax.swing.JLabel LBLMODELO;
    private javax.swing.JLabel LBLORIGEN;
    private javax.swing.JTable TRUTAS;
    private javax.swing.JTextField TXTCOD;
    private javax.swing.JTextField TXTCOSTO;
    private javax.swing.JTextField TXTPLANILLA;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
