/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.NPlanilla;
import Reportes.Reporte;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import proyecto_transporte.Controlador;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuPlanilla extends javax.swing.JFrame {
        NPlanilla planilla;
        int cod;
	float costoPlanilla;
	String fecha;
	String hora;
	float totalPasaje;
      	int codChofer;
	int idVehiculo;
	int nroItinerario;
    /**
     * Creates new form CuPlanilla
     */
    public CuPlanilla() throws ClassNotFoundException {
        initComponents();
        planilla=new NPlanilla();
         TableColumnModel columnModel = TPLANILLAS.getColumnModel();
         columnModel.getColumn(0).setPreferredWidth(10);
         columnModel.getColumn(1).setPreferredWidth(10);
         columnModel.getColumn(2).setPreferredWidth(10);
         columnModel.getColumn(3).setPreferredWidth(10);
         columnModel.getColumn(4).setPreferredWidth(40);
         columnModel.getColumn(5).setPreferredWidth(40);
         columnModel.getColumn(6).setPreferredWidth(40);
         columnModel.getColumn(7).setPreferredWidth(40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLORIGEN1 = new javax.swing.JLabel();
        LBLCOSTO1 = new javax.swing.JLabel();
        LBLMODELO1 = new javax.swing.JLabel();
        LBLCODIG1 = new javax.swing.JLabel();
        TXTHORA = new javax.swing.JTextField();
        TXTCOSTO = new javax.swing.JTextField();
        TXTITINERARIO = new javax.swing.JTextField();
        TXTTOTAL = new javax.swing.JTextField();
        LBLCODIG = new javax.swing.JLabel();
        TXTCOD = new javax.swing.JTextField();
        LBLORIGEN = new javax.swing.JLabel();
        TXTVEHICULO = new javax.swing.JTextField();
        LBLMODELO = new javax.swing.JLabel();
        TXTFECHA = new javax.swing.JTextField();
        BTNITINERARIOS = new javax.swing.JButton();
        BTNPLANILLAS = new javax.swing.JButton();
        BTNEDITAR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        TBNIMPRIMIR = new javax.swing.JButton();
        BTNREGISTRAR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TPLANILLAS = new javax.swing.JTable();
        BTNSALIR = new javax.swing.JButton();
        LBLCOSTO = new javax.swing.JLabel();
        TXTCHOFER = new javax.swing.JTextField();
        BTNNUEVO = new javax.swing.JButton();
        BTNCHOFERES = new javax.swing.JButton();
        BTNVEHICULOS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "REGISTRO DE PLANILLAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLORIGEN1.setText("TOTAL DE PASAJES( BS. )");
        jPanel1.add(LBLORIGEN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, -1, -1));

        LBLCOSTO1.setText("NRO. DE ITINERARIO");
        jPanel1.add(LBLCOSTO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        LBLMODELO1.setText("HORA");
        jPanel1.add(LBLMODELO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        LBLCODIG1.setText("COSTO");
        jPanel1.add(LBLCODIG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel1.add(TXTHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, -1));

        TXTCOSTO.setText("1");
        jPanel1.add(TXTCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 140, -1));
        jPanel1.add(TXTITINERARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 130, -1));

        TXTTOTAL.setText("0");
        jPanel1.add(TXTTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 130, -1));

        LBLCODIG.setText("CODIGO");
        jPanel1.add(LBLCODIG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(TXTCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, -1));

        LBLORIGEN.setText("CODIGO DE VEHICULO");
        jPanel1.add(LBLORIGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));
        jPanel1.add(TXTVEHICULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, -1));

        LBLMODELO.setText("FECHA");
        jPanel1.add(LBLMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel1.add(TXTFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 140, -1));

        BTNITINERARIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        BTNITINERARIOS.setText("ITINERARIOS");
        BTNITINERARIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNITINERARIOSActionPerformed(evt);
            }
        });
        jPanel1.add(BTNITINERARIOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 150, 40));

        BTNPLANILLAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock1.png"))); // NOI18N
        BTNPLANILLAS.setText("PLANILLAS");
        BTNPLANILLAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPLANILLASActionPerformed(evt);
            }
        });
        jPanel1.add(BTNPLANILLAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 150, 40));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 150, 40));

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 150, -1));

        TBNIMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_imprimir.gif"))); // NOI18N
        TBNIMPRIMIR.setText("Imprimir");
        TBNIMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBNIMPRIMIRActionPerformed(evt);
            }
        });
        jPanel1.add(TBNIMPRIMIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 150, -1));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 150, 40));

        TPLANILLAS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "COSTO", "FECHA", "HORA", "COD. CHOFER", "COD. VEHICULO", "NRO. ITINERARIO", "TOTAL DE PASAJES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TPLANILLAS.setMinimumSize(new java.awt.Dimension(180, 0));
        jScrollPane1.setViewportView(TPLANILLAS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 670, 260));

        BTNSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR.setText("SALLIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 150, 40));

        LBLCOSTO.setText("CODIGO DE CHOFER");
        jPanel1.add(LBLCOSTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));
        jPanel1.add(TXTCHOFER, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, -1));

        BTNNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNNUEVO.setText("  NUEVO  ");
        BTNNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNUEVOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 150, 40));

        BTNCHOFERES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        BTNCHOFERES.setText("CHOFERES");
        BTNCHOFERES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCHOFERESActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCHOFERES, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 150, 40));

        BTNVEHICULOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        BTNVEHICULOS.setText("VEHICULOS");
        BTNVEHICULOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVEHICULOSActionPerformed(evt);
            }
        });
        jPanel1.add(BTNVEHICULOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 840, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNITINERARIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNITINERARIOSActionPerformed
        try {
            // TODO add your handling code here:
            new CuItinerario().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuLugar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNITINERARIOSActionPerformed

    private void BTNPLANILLASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPLANILLASActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel modelo= (DefaultTableModel) TPLANILLAS.getModel();
            int filas=modelo.getRowCount();
            if (filas>0) {
                for (int i = 0; i < filas; i++) {
                    modelo.removeRow(0);
                }
            }
            String fecha=JOptionPane.showInputDialog(null, "INTRODUCIR UNA FECHA 'EJEMPLO 2016-06-15'");
            String[][] table=planilla.ListaDeItinerarios(fecha);            
            for (int i = 0; i <table.length ; i++) {
                modelo.addRow(new Object[]{table[i][0],table[i][1],table[i][2],table[i][3],table[i][5],table[i][6],table[i][7],table[i][4]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO EXISTEN PLANILLAS EN LA FECHA INTRODUCIDA");
        }
    }//GEN-LAST:event_BTNPLANILLASActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here:
        try {
            cod=Integer.valueOf(TXTCOD.getText());
            codChofer=Integer.valueOf(TXTCHOFER.getText());
            fecha=TXTFECHA.getText();
            idVehiculo=Integer.valueOf(TXTVEHICULO.getText());
            costoPlanilla=Float.valueOf(TXTCOSTO.getText());
            nroItinerario=Integer.valueOf(TXTITINERARIO.getText());
            totalPasaje=Float.valueOf(TXTTOTAL.getText());
            hora=TXTHORA.getText();
            String respuesta=planilla.actualizar(cod, costoPlanilla, fecha, hora, totalPasaje, nroItinerario, codChofer, idVehiculo);
            JOptionPane.showMessageDialog(null,respuesta);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"DATOS INVALIDOS "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            String[] table=planilla.Consultabuscar(TXTCOD.getText());
            TXTCOD.setText(table[0]);
            TXTCOSTO.setText(table[1]);
            TXTFECHA.setText(table[2]);
            TXTHORA.setText(table[3]);
            TXTTOTAL.setText(table[4]);
            TXTCHOFER.setText(table[5]);
            TXTVEHICULO.setText(table[6]);
            TXTITINERARIO.setText(table[7]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE ENCONTRO EL ITINERARIO ");
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        String resultado="";
        try {
            cod=Integer.valueOf(TXTCOD.getText());
            codChofer=Integer.valueOf(TXTCHOFER.getText());
            fecha=TXTFECHA.getText();
            idVehiculo=Integer.valueOf(TXTVEHICULO.getText());
            costoPlanilla=Float.valueOf(TXTCOSTO.getText());
            nroItinerario=Integer.valueOf(TXTITINERARIO.getText());
            totalPasaje=Float.valueOf(TXTTOTAL.getText());
            hora=TXTHORA.getText();
            resultado=planilla.insertar(cod, costoPlanilla, fecha, hora, totalPasaje,
                    nroItinerario, codChofer, idVehiculo);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,resultado+" "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNUEVOActionPerformed
        // TODO add your handling code here:
        TXTCHOFER.setText("");
        TXTFECHA.setText("");
        TXTHORA.setText("");
        TXTITINERARIO.setText("");
        TXTTOTAL.setText("0");
        TXTVEHICULO.setText("");
        TXTCOD.setText(planilla.ObetenerCodigoNuevo());
    }//GEN-LAST:event_BTNNUEVOActionPerformed

    private void BTNCHOFERESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCHOFERESActionPerformed
            try {
                // TODO add your handling code here:
                new CuPersona().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CuPlanilla.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_BTNCHOFERESActionPerformed

    private void BTNVEHICULOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVEHICULOSActionPerformed
            try {
                // TODO add your handling code here:
                new CuVehiculo().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CuPlanilla.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_BTNVEHICULOSActionPerformed

    private void TBNIMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBNIMPRIMIRActionPerformed
        // TODO add your handling code here:
         if(Controlador.esNumero(TXTCOD.getText()))  
            Reporte.Planilla(Integer.parseInt(TXTCOD.getText()));

    }//GEN-LAST:event_TBNIMPRIMIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuPlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuPlanilla().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CuPlanilla.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNCHOFERES;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNITINERARIOS;
    private javax.swing.JButton BTNNUEVO;
    private javax.swing.JButton BTNPLANILLAS;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JButton BTNVEHICULOS;
    private javax.swing.JLabel LBLCODIG;
    private javax.swing.JLabel LBLCODIG1;
    private javax.swing.JLabel LBLCOSTO;
    private javax.swing.JLabel LBLCOSTO1;
    private javax.swing.JLabel LBLMODELO;
    private javax.swing.JLabel LBLMODELO1;
    private javax.swing.JLabel LBLORIGEN;
    private javax.swing.JLabel LBLORIGEN1;
    private javax.swing.JButton TBNIMPRIMIR;
    private javax.swing.JTable TPLANILLAS;
    private javax.swing.JTextField TXTCHOFER;
    private javax.swing.JTextField TXTCOD;
    private javax.swing.JTextField TXTCOSTO;
    private javax.swing.JTextField TXTFECHA;
    private javax.swing.JTextField TXTHORA;
    private javax.swing.JTextField TXTITINERARIO;
    private javax.swing.JTextField TXTTOTAL;
    private javax.swing.JTextField TXTVEHICULO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
