/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Negocio.NReserva;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuReserva extends javax.swing.JFrame {
    NReserva reserva;
    int id;
    String fecha;
    String hora;
    static int nroBoleto;
    /**
     * Creates new form CuReserva
     */
    public CuReserva() throws ClassNotFoundException {
        initComponents();
        reserva=new NReserva();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BTNSALIR = new javax.swing.JButton();
        TXTBOLETO = new javax.swing.JTextField();
        TXTHORA = new javax.swing.JTextField();
        TXTCOD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTFECHA = new javax.swing.JTextField();
        BTNREGISTRAR = new javax.swing.JButton();
        BTNBUSCAR = new javax.swing.JButton();
        BTNEDITAR = new javax.swing.JButton();
        BTNNUEVO = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BTNMOSTRAR1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBOLETOS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNSALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 150, 40));
        jPanel1.add(TXTBOLETO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, -1));
        jPanel1.add(TXTHORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 140, -1));
        jPanel1.add(TXTCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("NRO. DE BOLETO");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("FECHA");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CODIGO");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("HORA");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(TXTFECHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 140, -1));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 150, 40));

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 150, 40));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 150, 40));

        BTNNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNNUEVO.setText("    NUEVO");
        BTNNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNUEVOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 150, 40));

        jTabbedPane1.addTab("Registro De Reserva", jPanel1);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNMOSTRAR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/stock1.png"))); // NOI18N
        BTNMOSTRAR1.setText("MOSTRAR");
        BTNMOSTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMOSTRAR1ActionPerformed(evt);
            }
        });
        jPanel5.add(BTNMOSTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 40));

        TBOLETOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "FECHA", "HORA", "NRO. DE BOLETO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TBOLETOS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TBOLETOS.setMinimumSize(new java.awt.Dimension(0, 0));
        TBOLETOS.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(TBOLETOS);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 610, 390));

        jTabbedPane1.addTab("Lista De Reservas", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 630, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        try {
            id=Integer.valueOf(TXTCOD.getText());
            fecha=TXTFECHA.getText();
            hora=TXTHORA.getText();
            nroBoleto=Integer.valueOf(TXTBOLETO.getText());
            String resultado=reserva.insertar(id, fecha, hora, nroBoleto);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"DATOS INVALIDOS: "+ e.getMessage());
        }
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        try {
            if (TXTBOLETO.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "INTRODUZCA CODIGO DE BOLETO");
                return;
            }
            String[] resultado=reserva.Consultabuscar(TXTBOLETO.getText());
            TXTCOD.setText(resultado[0]);
            TXTFECHA.setText(resultado[1]);
            TXTHORA.setText(resultado[2]);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO EXISTE RESERVA PARA EL BOLETO");
        }
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here
        try {
            id=Integer.valueOf(TXTCOD.getText());
            fecha=TXTFECHA.getText();
            hora=TXTHORA.getText();
            String resultado=reserva.acutalizar(id, fecha,hora);
            JOptionPane.showMessageDialog(null, resultado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"NO SE ENCONTRO REGISTROS DE BOLETOS EN LA FECHA INTRODUCIDA ");
        }

    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void BTNNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNUEVOActionPerformed
        // TODO add your handling code here:
        TXTHORA.setText("");
        TXTBOLETO.setText(String.valueOf(nroBoleto));
        TXTFECHA.setText("");
        TXTCOD.setText(reserva.ObetenerCodigoNuevo());
    }//GEN-LAST:event_BTNNUEVOActionPerformed

    private void BTNMOSTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMOSTRAR1ActionPerformed
        // TODO add your handling code here:
        try {
            String fecha=JOptionPane.showInputDialog(null,"INTRODUZCA LA FECHA DE LAS RESERVAS");
            String[][] table=reserva.ListaDeReservas("'"+fecha+"'");
            DefaultTableModel modelo= (DefaultTableModel) TBOLETOS.getModel();
            int Tfila=modelo.getRowCount();
            if (Tfila>0) {
                for (int i = 0; i <Tfila ; i++) {
                    modelo.removeRow(0);
                }
            }
            int tuplas=table.length;
            for (int i = 0; i < tuplas; i++) {
                modelo.addRow(new Object[]{table[i][0],table[i][1],table[i][2],table[i][3]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS INVALIDOS "+e.getMessage());
        }
    }//GEN-LAST:event_BTNMOSTRAR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuReserva().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CuReserva.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNMOSTRAR1;
    private javax.swing.JButton BTNNUEVO;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JTable TBOLETOS;
    private javax.swing.JTextField TXTBOLETO;
    private javax.swing.JTextField TXTCOD;
    private javax.swing.JTextField TXTFECHA;
    private javax.swing.JTextField TXTHORA;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
