/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.DVehiculo;
import Negocio.NSeguro;
import Negocio.NVehiculo;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author FRANKLIN SALAS
 */
public class CuVehiculo extends javax.swing.JFrame {
        int id;
	String Placa;
	int Capacidad;
	String Tipo;
	int Modelo;
	int codPersona;
	int idEstado;
        
        int codSoat;
	String otroSeguro;
	int anio;
    NVehiculo vehiculo;
    NSeguro seguro;
    /**
     * Creates new form CuVehiculo
     */
    public CuVehiculo() throws ClassNotFoundException {
        initComponents();
        vehiculo=new NVehiculo();
        seguro=new NSeguro();
        TableColumnModel columnModel = TVEHICULO.getColumnModel();
         columnModel.getColumn(0).setPreferredWidth(15);
         columnModel.getColumn(1).setPreferredWidth(15);
         columnModel.getColumn(2).setPreferredWidth(15);
         columnModel.getColumn(3).setPreferredWidth(15);
         columnModel.getColumn(4).setPreferredWidth(15);
         columnModel.getColumn(5).setPreferredWidth(40);
         columnModel.getColumn(6).setPreferredWidth(40);

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BTNBUSCAR = new javax.swing.JButton();
        TXTOTRO = new javax.swing.JTextField();
        TXTANIO1 = new javax.swing.JTextField();
        TXTCAPACIDAD = new javax.swing.JTextField();
        BTNEDITAR = new javax.swing.JButton();
        RBCREDINFORM = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        RBSOAT = new javax.swing.JRadioButton();
        TXTCODPERSONA1 = new javax.swing.JTextField();
        BTNREGISTRAR = new javax.swing.JButton();
        LBLPLACA = new javax.swing.JLabel();
        BTNESTADO = new javax.swing.JButton();
        TXTESTADO = new javax.swing.JTextField();
        LBLCAPACIDAD = new javax.swing.JLabel();
        CBTIPO = new javax.swing.JComboBox();
        TXTPLACA = new javax.swing.JTextField();
        LBLPLACA2 = new javax.swing.JLabel();
        TXTCOD = new javax.swing.JTextField();
        LBLMODELO = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBLMODELO2 = new javax.swing.JLabel();
        LBLCODESTADO = new javax.swing.JLabel();
        TXTMODELO = new javax.swing.JTextField();
        BTNNUEVO = new javax.swing.JButton();
        BTNSALIR1 = new javax.swing.JButton();
        BTNSALIR2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BTNMOSTRAR1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TVEHICULO = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNBUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search2.png"))); // NOI18N
        BTNBUSCAR.setText("BUSCAR");
        BTNBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 130, 40));
        jPanel1.add(TXTOTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 100, -1));
        jPanel1.add(TXTANIO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 70, -1));
        jPanel1.add(TXTCAPACIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 140, -1));

        BTNEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 120, 40));

        RBCREDINFORM.setText("CREDINFORM");
        RBCREDINFORM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCREDINFORMActionPerformed(evt);
            }
        });
        jPanel1.add(RBCREDINFORM, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SELECCIONAR SEGUROS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        RBSOAT.setText("SOAT");
        jPanel1.add(RBSOAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));
        jPanel1.add(TXTCODPERSONA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 140, -1));

        BTNREGISTRAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/onebit_20.png"))); // NOI18N
        BTNREGISTRAR.setText("REGISTRAR");
        BTNREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNREGISTRARActionPerformed(evt);
            }
        });
        jPanel1.add(BTNREGISTRAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 150, 40));

        LBLPLACA.setText("PLACA");
        jPanel1.add(LBLPLACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        BTNESTADO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        BTNESTADO.setText("ESTADOS");
        BTNESTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNESTADOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 40));
        jPanel1.add(TXTESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 140, -1));

        LBLCAPACIDAD.setText("CAPACIDAD");
        jPanel1.add(LBLCAPACIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        CBTIPO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TIPO DE VEHICULO", "NOAH", "MINIBUS" }));
        jPanel1.add(CBTIPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 150, -1));
        jPanel1.add(TXTPLACA, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 140, -1));

        LBLPLACA2.setText("IDENTIFICADOR");
        jPanel1.add(LBLPLACA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));
        jPanel1.add(TXTCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 140, -1));

        LBLMODELO.setText("MODELO");
        jPanel1.add(LBLMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel5.setText("AÑO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        LBLMODELO2.setText("CODIGO DUEÑO");
        jPanel1.add(LBLMODELO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        LBLCODESTADO.setText("CODIGO DEL ESTADO");
        jPanel1.add(LBLCODESTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));
        jPanel1.add(TXTMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 140, -1));

        BTNNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonCrearNuevo.gif"))); // NOI18N
        BTNNUEVO.setText("  NUEVO");
        BTNNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNUEVOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNNUEVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 120, 40));

        BTNSALIR1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        BTNSALIR1.setText("PERSONAS");
        BTNSALIR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIR1ActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSALIR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 140, 40));

        BTNSALIR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        BTNSALIR2.setText("SALLIR");
        BTNSALIR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIR2ActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSALIR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VIP_Car_Rentz_Cars_Noah_2006_web-Custom.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 370, 290));

        jTabbedPane1.addTab("REGISTRO DE VEHICULOS", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNMOSTRAR1.setText("MOSTRAR");
        BTNMOSTRAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMOSTRAR1ActionPerformed(evt);
            }
        });
        jPanel2.add(BTNMOSTRAR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        TVEHICULO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PLACA", "CAPACIDAD", "TIPO", "MODELO", "CODIGO SOCIO", "CODIGO ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TVEHICULO.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TVEHICULO.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(TVEHICULO);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 700, 290));

        jTabbedPane1.addTab("LISTA DE VEHICULOS", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 710, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNMOSTRAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMOSTRAR1ActionPerformed
        // TODO add your handling code here:
        try {
            //        String cod=JOptionPane.showInputDialog(null,"INTRODUZCA CODIGO");
            String[][] table=vehiculo.listaDeVehiculos();
            DefaultTableModel modelo= (DefaultTableModel) TVEHICULO.getModel();
            int Tfila=modelo.getRowCount();
            if (Tfila>0) {
                for (int i = 0; i <Tfila ; i++) {
                    modelo.removeRow(0);
                }
            }
            int tuplas=table.length;
            for (int i = 0; i < tuplas; i++) {
                modelo.addRow(new Object[]{table[i][0],table[i][1],table[i][2],table[i][3],table[i][4],table[i][5],table[i][6]});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR DEL SISTEMA "+e.getMessage());
        }
    }//GEN-LAST:event_BTNMOSTRAR1ActionPerformed

    private void BTNSALIR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIR1ActionPerformed
        // TODO add your handling code here:
        CuPersona persona;
        try {
            persona = new CuPersona();
            persona.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BTNSALIR1ActionPerformed

    private void BTNESTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNESTADOActionPerformed
        // TODO add your handling code here:
        CuEstado estado;
        try {
            estado = new CuEstado();
            estado.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CuVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNESTADOActionPerformed

    private void BTNREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNREGISTRARActionPerformed
        // TODO add your handling code here:
        try {
        id=Integer.valueOf(TXTCOD.getText());
	Placa=TXTPLACA.getText();
	Capacidad=Integer.valueOf(TXTCAPACIDAD.getText());
	Tipo=CBTIPO.getSelectedItem().toString();
	Modelo=Integer.valueOf(TXTMODELO.getText());
	codPersona=Integer.valueOf(TXTCODPERSONA1.getText());
	idEstado=Integer.valueOf(TXTESTADO.getText());
       	anio=Integer.valueOf(TXTANIO1.getText());
        otroSeguro=TXTOTRO.getText();
        if (RBSOAT.isSelected() && otroSeguro.length()!=0) {
            codSoat=111;
            vehiculo.insertar(id, Placa, Capacidad, Tipo, Modelo, codPersona, idEstado, codSoat, otroSeguro, anio);
        }else{
                if (RBSOAT.isSelected()) {
                    codSoat=111;
                }else{
                    JOptionPane.showMessageDialog(null, "SELECCIONE SOAT");
                    return;
                }
                if (RBCREDINFORM.isSelected()) {
                    this.otroSeguro="222";
                }else{
                    JOptionPane.showMessageDialog(null, "SELECCIONE CREDINFORM");
                    return;
                }
                vehiculo.insertar(id, Placa, Capacidad, Tipo, Modelo, codPersona, idEstado, codSoat, otroSeguro, anio);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS INVALIDOS "+e.getMessage());
        }
        
    }//GEN-LAST:event_BTNREGISTRARActionPerformed

    private void BTNBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARActionPerformed
        // TODO add your handling code here:
        try {
            String[] v=vehiculo.Consultabuscar(TXTPLACA.getText(),TXTANIO1.getText());
            TXTCOD.setText(v[0]);
            TXTPLACA.setText(v[1]);
            TXTCAPACIDAD.setText(v[2]);
            CBTIPO.setSelectedItem(v[3]);
            TXTMODELO.setText(v[4]);;
            TXTCODPERSONA1.setText(v[5]);
            TXTESTADO.setText(v[6]);
            if (v[7].compareTo("111")==0) {
                RBSOAT.setSelected(true);
            }
            if (v[9].compareTo("222")==0) {
                RBCREDINFORM.setSelected(true);
            }else{
                TXTOTRO.setText(seguro.Consultabuscar(v[9])[1]);
            }        
            if (v[8].compareTo(v[10])==0) {
                anio=Integer.valueOf(TXTANIO1.getText());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "VEHICULO NO ENCONTADO");
        }
        
	
        
    }//GEN-LAST:event_BTNBUSCARActionPerformed

    private void BTNSALIR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIR2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSALIR2ActionPerformed
    
    public void limpiar(){
        TXTANIO1.setText("");
        TXTCAPACIDAD.setText("");
        TXTCOD.setText("");
        TXTCODPERSONA1.setText("");
        TXTESTADO.setText("");
        TXTMODELO.setText("");
        TXTPLACA.setText("");
        CBTIPO.setSelectedIndex(0);
        RBCREDINFORM.setSelected(false);
        RBSOAT.setSelected(false);        
    }
    
    private void BTNNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNUEVOActionPerformed
        // TODO add your handling code here:
        limpiar();
        TXTCOD.setText(String.valueOf(vehiculo.ObetenerCodigoNuevo()));        
    }//GEN-LAST:event_BTNNUEVOActionPerformed

    private void RBCREDINFORMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCREDINFORMActionPerformed
        // TODO add your handling code here:
        if (RBCREDINFORM.isSelected()) {
            TXTOTRO.setEnabled(false);
        }else{
            TXTOTRO.setEnabled(true);
        }
        
    }//GEN-LAST:event_RBCREDINFORMActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed
        // TODO add your handling code here:
        try {
            id=Integer.valueOf(TXTCOD.getText());
            Placa=TXTPLACA.getText();
            Capacidad=Integer.valueOf(TXTCAPACIDAD.getText());
            Tipo=CBTIPO.getSelectedItem().toString();
            Modelo=Integer.valueOf(TXTMODELO.getText());
            codPersona=Integer.valueOf(TXTCODPERSONA1.getText());
            idEstado=Integer.valueOf(TXTESTADO.getText());
            anio=Integer.valueOf(TXTANIO1.getText());
            otroSeguro=TXTOTRO.getText();
        if (RBSOAT.isSelected() && otroSeguro.length()!=0) {
            codSoat=111;
            String resultado=vehiculo.acutalizar(id, Placa, Capacidad, Tipo, Modelo, codPersona, idEstado, codSoat, otroSeguro, anio);
            JOptionPane.showMessageDialog(null, resultado);
        }else{
                if (RBSOAT.isSelected()) {
                    codSoat=111;
                }else{
                    JOptionPane.showMessageDialog(null, "SELECCIONE SOAT");
                    return;
                }
                if (RBCREDINFORM.isSelected()) {
                    otroSeguro="222";
                }else{
                    JOptionPane.showMessageDialog(null, "SELECCIONE CREDINFORM");
                    return;
                }
                String resultado=vehiculo.acutalizar(id, Placa, Capacidad, Tipo, Modelo, codPersona, idEstado, codSoat, otroSeguro, anio);
                JOptionPane.showMessageDialog(null, resultado);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS INVALIDOS "+e.getMessage());
        }
    }//GEN-LAST:event_BTNEDITARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CuVehiculo().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CuVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBUSCAR;
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton BTNESTADO;
    private javax.swing.JButton BTNMOSTRAR1;
    private javax.swing.JButton BTNNUEVO;
    private javax.swing.JButton BTNREGISTRAR;
    private javax.swing.JButton BTNSALIR1;
    private javax.swing.JButton BTNSALIR2;
    private javax.swing.JComboBox CBTIPO;
    private javax.swing.JLabel LBLCAPACIDAD;
    private javax.swing.JLabel LBLCODESTADO;
    private javax.swing.JLabel LBLMODELO;
    private javax.swing.JLabel LBLMODELO2;
    private javax.swing.JLabel LBLPLACA;
    private javax.swing.JLabel LBLPLACA2;
    private javax.swing.JRadioButton RBCREDINFORM;
    private javax.swing.JRadioButton RBSOAT;
    private javax.swing.JTable TVEHICULO;
    private javax.swing.JTextField TXTANIO1;
    private javax.swing.JTextField TXTCAPACIDAD;
    private javax.swing.JTextField TXTCOD;
    private javax.swing.JTextField TXTCODPERSONA1;
    private javax.swing.JTextField TXTESTADO;
    private javax.swing.JTextField TXTMODELO;
    private javax.swing.JTextField TXTOTRO;
    private javax.swing.JTextField TXTPLACA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
