/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidad.GrupoPrivilegio;
import Negocio.NGrupo;
import Negocio.NGrupoPrivilegio;
import java.awt.event.ItemEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import proyecto_transporte.Controlador;

/**
 *
 * @author FRANKLIN SALAS
 */
public class Privilegios extends javax.swing.JFrame {

    /**
     * Creates new form Privilegios
     */
   
    public Privilegios() {
        initComponents();
            this.setLocationRelativeTo(this);
           // grupos();
            inicio();
           // Privilegios(combGrupos.getSelectedItem().toString());
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chAdministracion = new javax.swing.JCheckBox();
        chPrivilegios = new javax.swing.JCheckBox();
        chVehiculo = new javax.swing.JCheckBox();
        chSeguro = new javax.swing.JCheckBox();
        chPersonal = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chBoleto = new javax.swing.JCheckBox();
        chCliente = new javax.swing.JCheckBox();
        chReserva = new javax.swing.JCheckBox();
        chGuia = new javax.swing.JCheckBox();
        chEncomienda = new javax.swing.JCheckBox();
        chNota = new javax.swing.JCheckBox();
        chEquipaje = new javax.swing.JCheckBox();
        ChAtencionClientes = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chReporte = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        chItinerario = new javax.swing.JCheckBox();
        chRuta = new javax.swing.JCheckBox();
        chLugar = new javax.swing.JCheckBox();
        chPlanilla = new javax.swing.JCheckBox();
        chhojaSalida = new javax.swing.JCheckBox();
        chHojaLLegada = new javax.swing.JCheckBox();
        chViajes = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        combGrupos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Administracion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chPrivilegios.setText("Gestionar Privilegios");

        chVehiculo.setText("Gestionar Vehiculo");

        chSeguro.setText("Gestionar Seguro");

        chPersonal.setText("Gestionar Personal");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/system1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(chAdministracion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chPrivilegios)
                    .addComponent(chPersonal))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chVehiculo)
                    .addComponent(chSeguro))
                .addGap(209, 209, 209))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chVehiculo)
                        .addComponent(chPrivilegios)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chAdministracion)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chSeguro)
                    .addComponent(chPersonal))
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Atencion al Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chBoleto.setText("Gestionar Boleto");

        chCliente.setText("Gestionar Cliente");

        chReserva.setText("Gestionar Reserva");

        chGuia.setText("Gestionar Guia");

        chEncomienda.setText("Gestionar Encomienda");

        chNota.setText("Gestionar Nota");

        chEquipaje.setText("Gestionar Equipaje");
        chEquipaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chEquipajeActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/User.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(143, 143, 143)
                .addComponent(chBoleto)
                .addGap(56, 56, 56)
                .addComponent(chGuia)
                .addGap(76, 76, 76)
                .addComponent(chNota)
                .addGap(96, 96, 96)
                .addComponent(chReserva))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ChAtencionClientes))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(chCliente)
                .addGap(56, 56, 56)
                .addComponent(chEncomienda)
                .addGap(40, 40, 40)
                .addComponent(chEquipaje))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chBoleto)
                            .addComponent(chGuia)
                            .addComponent(chNota)
                            .addComponent(chReserva))))
                .addGap(2, 2, 2)
                .addComponent(ChAtencionClientes)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chCliente)
                    .addComponent(chEncomienda)
                    .addComponent(chEquipaje))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Reporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nota.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chReporte)
                    .addComponent(jLabel5))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chReporte)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Viajes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        chItinerario.setText("Gestionar Itinerario");

        chRuta.setText("Gestionar Ruta");

        chLugar.setText("Gestionar Lugar");

        chPlanilla.setText("Gestionar Planilla");

        chhojaSalida.setText("Gestionar Hoja de Salida");

        chHojaLLegada.setText("Gestionar Hoja de LLegada");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Documents.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(141, 141, 141)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chItinerario)
                            .addComponent(chRuta))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chLugar)
                            .addComponent(chPlanilla))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chhojaSalida)
                            .addComponent(chHojaLLegada)))
                    .addComponent(chViajes))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chItinerario)
                            .addComponent(chLugar)
                            .addComponent(chhojaSalida))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chRuta)
                            .addComponent(chPlanilla)
                            .addComponent(chHojaLLegada)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chViajes)))
                .addGap(39, 39, 39))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        combGrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combGruposItemStateChanged(evt);
            }
        });

        jLabel1.setText("Seleccione un Grupo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(combGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(combGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void grupos(){
   combGrupos.setModel(NGrupo.obtener());
    
    
    }
    private void Privilegios(String grupo){

//List<GrupoPrivilegio> lista= NGrupoPrivilegio.obtener(grupo);
int lista [] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,30};
    for (int lista1 : lista) {
    switch(lista1){
        case 1: chAdministracion.setSelected(true);  break;
        case 2: chPrivilegios.setSelected(true);  break;
        case 3: chPersonal.setSelected(true);  break;
        case 4: chVehiculo.setSelected(true);  break;
        case 5: chSeguro.setSelected(true); break;
        case 10:ChAtencionClientes.setSelected(true);   break;
        case 11: chBoleto.setSelected(true); break;
        case 12: chCliente.setSelected(true); break;
        case 13: chReserva.setSelected(true);  break;
        case 14: chGuia.setSelected(true);  break;
        case 15: chEncomienda.setSelected(true); break;
        case 16: chNota.setSelected(true);  break;
        case 17: chEquipaje.setSelected(true); break;
        case 20: chViajes.setSelected(true);  break;
        case 21: chItinerario.setSelected(true);  break;
        case 22: chRuta.setSelected(true);  break;
        case 23: chLugar.setSelected(true);  break;
        case 24: chPlanilla.setSelected(true);  break;
        case 25: chhojaSalida.setSelected(true);  break;
        case 26: chHojaLLegada.setSelected(true);  break;
        case 30: chReporte.setSelected(true);   break;
          
        default: break;
    }            
    }
}
 public void inicio(){
 chAdministracion.setSelected(false); 
 chPrivilegios.setSelected(false);
 chPersonal.setSelected(false); 
 chViajes.setSelected(false);
  chVehiculo.setSelected(false);
 chSeguro.setSelected(false); 
 ChAtencionClientes.setSelected(false);  
 chBoleto.setSelected(false);
 chCliente.setSelected(false);
 chReserva.setSelected(false); 
 chGuia.setSelected(false); 
 chEncomienda.setSelected(false);
 chNota.setSelected(false); 
 chEquipaje.setSelected(false);
 chViajes.setSelected(false);
 chItinerario.setSelected(false); 
  chRuta.setSelected(false);
  chLugar.setSelected(false);  
 chPlanilla.setSelected(false); 
 chhojaSalida.setSelected(false);
    chHojaLLegada.setSelected(false);
    chReporte.setSelected(false);   
          
 
 
 
 }   
    
 public List<GrupoPrivilegio> grupoPrivilegiosLis(){
  List<GrupoPrivilegio> listGrupoP=new LinkedList<>();

   if(chAdministracion.isSelected()){
   listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,1));  }
 if(chPrivilegios.isSelected())
 {  listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,2));}
if( chPersonal.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,3));}
  if(chVehiculo.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,4));}
 if(chSeguro.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,5));}
 if(ChAtencionClientes.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,10));}
 if(chBoleto.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,11));}
 if(chCliente.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,12));}
 if(chReserva.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,13));}
 if(chGuia.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,14));}
 if(chEncomienda.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,15));}
 if(chNota.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,16));}
 if(chEquipaje.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,17));}
 if(chViajes.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,20));}
 
 if(chItinerario.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,21));}
  if(chRuta.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,22));}
 if(chLugar.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,23));}
 if(chPlanilla.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,24));}
if(chhojaSalida.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,25));}
  if( chHojaLLegada.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,26));}
   if( chReporte.isSelected()){ listGrupoP.add(new GrupoPrivilegio(combGrupos.getSelectedIndex()+1,30));}
 

 return listGrupoP;
 }
    
    private void chEquipajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chEquipajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chEquipajeActionPerformed

    private void combGruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combGruposItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()== ItemEvent.SELECTED)
        {  Object item = evt.getItem();
          inicio();
            Privilegios(item.toString());
        
        }
    }//GEN-LAST:event_combGruposItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Guardar los Cambios");
        if(showConfirmDialog == JOptionPane.YES_OPTION)
  NGrupoPrivilegio.insetar(   grupoPrivilegiosLis());
        
       
        Object item = combGrupos.getSelectedItem();
          inicio();
            Privilegios(item.toString());
        
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Privilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Privilegios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChAtencionClientes;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chAdministracion;
    private javax.swing.JCheckBox chBoleto;
    private javax.swing.JCheckBox chCliente;
    private javax.swing.JCheckBox chEncomienda;
    private javax.swing.JCheckBox chEquipaje;
    private javax.swing.JCheckBox chGuia;
    private javax.swing.JCheckBox chHojaLLegada;
    private javax.swing.JCheckBox chItinerario;
    private javax.swing.JCheckBox chLugar;
    private javax.swing.JCheckBox chNota;
    private javax.swing.JCheckBox chPersonal;
    private javax.swing.JCheckBox chPlanilla;
    private javax.swing.JCheckBox chPrivilegios;
    private javax.swing.JCheckBox chReporte;
    private javax.swing.JCheckBox chReserva;
    private javax.swing.JCheckBox chRuta;
    private javax.swing.JCheckBox chSeguro;
    private javax.swing.JCheckBox chVehiculo;
    private javax.swing.JCheckBox chViajes;
    private javax.swing.JCheckBox chhojaSalida;
    private javax.swing.JComboBox combGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
